export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  DRIVER = 'DRIVER',
  STORE_STAFF = 'STORE_STAFF',
  STORE_ADMIN = 'STORE_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum OrderStatus {
  PLACED = 'PLACED',
  ACCEPTED = 'ACCEPTED',
  PREPARING = 'PREPARING',
  READY_FOR_DISPATCH = 'READY_FOR_DISPATCH',
  ASSIGNED_TO_BATCH = 'ASSIGNED_TO_BATCH',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  COD = 'COD',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
}

export enum BatchStatus {
  READY = 'READY',
  BATCHED = 'BATCHED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SlotStatus {
  UPCOMING = 'UPCOMING',
  OPEN = 'OPEN',
  FULL = 'FULL',
  CLOSED = 'CLOSED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum DriverStatus {
  AVAILABLE = 'AVAILABLE',
  BUSY = 'BUSY',
  OFFLINE = 'OFFLINE',
  INACTIVE = 'INACTIVE',
}

export enum InventoryMovementType {
  ORDER_RESERVATION = 'ORDER_RESERVATION',
  ORDER_CANCELLATION = 'ORDER_CANCELLATION',
  MANUAL_ADD = 'MANUAL_ADD',
  MANUAL_REMOVE = 'MANUAL_REMOVE',
  ADJUSTMENT = 'ADJUSTMENT',
  RESTOCK = 'RESTOCK',
}

export enum OutboxStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export enum OutboxEventType {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_ACCEPTED = 'ORDER_ACCEPTED',
  ORDER_READY = 'ORDER_READY',
  ORDER_BATCHED = 'ORDER_BATCHED',
  BATCH_ASSIGNED = 'BATCH_ASSIGNED',
  BATCH_DISPATCHED = 'BATCH_DISPATCHED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  INVENTORY_LOW = 'INVENTORY_LOW',
  INVENTORY_UPDATED = 'INVENTORY_UPDATED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  INVOICE_GENERATION_REQUESTED = 'INVOICE_GENERATION_REQUESTED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  INVENTORY_ADJUSTMENT = 'INVENTORY_ADJUSTMENT',
  DRIVER_ASSIGNMENT = 'DRIVER_ASSIGNMENT',
  OTP_VERIFY = 'OTP_VERIFY',
  BATCH_DISPATCH = 'BATCH_DISPATCH',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}
